import { FileText, BarChart2, Package, Users } from "lucide-react";
import type { User, Project, Task } from "./types";

export const users: User[] = [
  { id: "user-1", name: "Sarah Lee", avatarUrl: "https://picsum.photos/seed/1/40/40", email: "sarah@example.com" },
  { id: "user-2", name: "Mike Johnson", avatarUrl: "https://picsum.photos/seed/2/40/40", email: "mike@example.com" },
  { id: "user-3", name: "Emily Chen", avatarUrl: "https://picsum.photos/seed/3/40/40", email: "emily@example.com" },
  { id: "user-4", name: "David Rodriguez", avatarUrl: "https://picsum.photos/seed/4/40/40", email: "david@example.com" },
];

export const projects: Project[] = [
  { id: "proj-1", name: "Website Redesign", icon: FileText },
  { id: "proj-2", name: "Mobile App", icon: Package },
  { id: "proj-3", name: "Marketing Campaign", icon: BarChart2 },
  { id: "proj-4", name: "Team Onboarding", icon: Users },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Design homepage mockups",
    description: "Create high-fidelity mockups for the new website homepage.",
    status: "inprogress",
    priority: "high",
    deadline: new Date(new Date().setDate(new Date().getDate() + 3)),
    assigneeId: "user-1",
    projectId: "proj-1",
    tags: ["design", "ui/ux"],
  },
  {
    id: "task-2",
    title: "Develop login functionality",
    description: "Implement JWT-based authentication for the mobile app.",
    status: "inprogress",
    priority: "high",
    deadline: new Date(new Date().setDate(new Date().getDate() + 5)),
    assigneeId: "user-3",
    projectId: "proj-2",
    tags: ["development", "auth"],
  },
  {
    id: "task-3",
    title: "Plan social media content",
    description: "Outline content calendar for the next month's marketing campaign.",
    status: "todo",
    priority: "medium",
    deadline: new Date(new Date().setDate(new Date().getDate() + 7)),
    assigneeId: "user-2",
    projectId: "proj-3",
    tags: ["marketing", "content"],
  },
  {
    id: "task-4",
    title: "Finalize homepage design",
    description: "Incorporate feedback and finalize the homepage design.",
    status: "done",
    priority: "high",
    deadline: new Date(new Date().setDate(new Date().getDate() - 2)),
    assigneeId: "user-1",
    projectId: "proj-1",
    tags: ["design", "ui/ux"],
  },
  {
    id: "task-5",
    title: "Setup CI/CD pipeline",
    status: "todo",
    priority: "medium",
    assigneeId: "user-3",
    projectId: "proj-2",
    tags: ["devops", "development"],
  },
  {
    id: "task-6",
    title: "Create ad copy for social media",
    status: "todo",
    priority: "low",
    deadline: new Date(new Date().setDate(new Date().getDate() + 10)),
    assigneeId: "user-2",
    projectId: "proj-3",
    tags: ["marketing", "copywriting"],
  },
  {
    id: "task-7",
    title: "User testing for prototype",
    description: "Conduct user testing sessions for the website prototype.",
    status: "done",
    priority: "medium",
    deadline: new Date(new Date().setDate(new Date().getDate() - 5)),
    assigneeId: "user-4",
    projectId: "proj-1",
    tags: ["research", "ux"],
  },
  {
    id: "task-8",
    title: "Fix push notification bug",
    description: "Investigate and fix the bug where push notifications are not being delivered on Android.",
    status: "inprogress",
    priority: "high",
    deadline: new Date(new Date().setDate(new Date().getDate() + 1)),
    assigneeId: "user-3",
    projectId: "proj-2",
    tags: ["bug", "mobile"],
  },
];
